### ISSUE TITLE
Custom theme problems

### ISSUE THREAD

**Issue by omnicons** [Giingu/DiscordPlus#5]
It appears that there's a few issues that have come up with your custom theme here. In the center of the screen there's a toggle always visible, and toggling it disables the page's inputs. Several UI elements like viewing the server menu also breaks the formatting.

**Comment by kckarnige** [comment]
I feel like some of the things you're mentioning are intentional, like the toggle and it's placement

**Comment by omnicons** [comment]
I'm not using this anymore, but the toggle covered the main content and wasn't attached to any part of the UI really. It was just hovering on the left side of the main chat portion of the window in the direct center. It has no function (that I can tell) since it doesn't respond to being clicked. I was able to replicate it on several computers and it's why I stopped using the theme!

**Comment by Giingu** [comment]
DiscordPlus+ is now back!
