### ISSUE TITLE
New Discord Update = Code 100% Broken

### ISSUE THREAD

**Issue by ForeverPyrite** [Giingu/DiscordPlus#6]
I have no idea what happened, but:
![image](https://user-images.githubusercontent.com/51493121/115754142-ea232f00-a369-11eb-8f2b-31051ff22ddc.png)
The only thing that is affected by the userscript is the "Change Account" menu option (as shown above), otherwise the script is 100% broken...did you guys create a new release or anything?

(P.S. Closing my issues from @Devan-Vaughn )

**Comment by Spongeyboi** [comment]
broke for me too

**Comment by ForeverPyrite** [comment]
Glad I wasn't the only one, I had also enabled the experimental dark mode on my Chromebook (chrome://flags then just enabled all the dark mode things) and thought that might've caused it. Turns out it can't because it barely affects Discord as it is already on dark mode.

**Comment by Giingu** [comment]
DiscordPlus+ is now back!
